/* LayoutBeep: нативное Win32-приложение.
   Исходник разделён на последовательные include-фрагменты только для удобства хранения. */
#include "LayoutBeep_01.inc"
#include "LayoutBeep_02.inc"
#include "LayoutBeep_03.inc"
#include "LayoutBeep_04.inc"
#include "LayoutBeep_05.inc"
#include "LayoutBeep_06.inc"
#include "LayoutBeep_07.inc"
#include "LayoutBeep_08.inc"
#include "LayoutBeep_09.inc"
#include "LayoutBeep_10.inc"
#include "LayoutBeep_11.inc"
#include "LayoutBeep_12.inc"
#include "LayoutBeep_13.inc"
#include "LayoutBeep_14.inc"
#include "LayoutBeep_18.inc"
#include "LayoutBeep_15.inc"
#include "LayoutBeep_16.inc"
#include "LayoutBeep_17.inc"
